'use strict';
const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
const elementos = {};
const elemento = id => elementos[id] || (elementos[id] = {textContent: '', disabled: false, style: {}, focus() {}});
let previa, pedido, destino, recarregou = false;
const modal = {modal() {}, on() {return this;}};
const $ = () => modal;
$.getJSON = () => ({done(callback) {previa = callback; return this;}, fail() {return this;}});
$.ajax = opcoes => {pedido = opcoes; return {done(callback) {destino = callback; return this;}, fail() {return this;}};};
const window = {location: {reload() {recarregou = true;}}, alert() {}};
vm.runInNewContext(fs.readFileSync('dist/js/confirmacao-exclusao.js', 'utf8'), {
    window, jQuery: $, document: {getElementById: elemento, documentElement: {contains() {return true;}}}
});
window.excluir_terceiro(7);
previa({nome: 'Animal', pode_excluir: false, ativo: true, csrf_token: 'token', vinculos: [{tipo: 'Crias', quantidade: 2}]});
assert.strictEqual(elemento('confirmacao-exclusao-prosseguir').disabled, true);
assert.match(elemento('confirmacao-exclusao-descricao').textContent, /Crias: 2/);
elemento('confirmacao-exclusao-prosseguir').onclick();
assert.strictEqual(pedido, undefined);
assert.strictEqual(elemento('confirmacao-exclusao-inativar').style.display, '');
elemento('confirmacao-exclusao-inativar').onclick();
assert.strictEqual(pedido.data.acao, 'inativar');
assert.strictEqual(pedido.data.csrf_token, 'token');
destino();
assert.strictEqual(recarregou, true);
window.excluir_terceiro(7);
previa({nome: 'Animal', pode_excluir: false, ativo: false, vinculos: [{tipo: 'Crias', quantidade: 2}]});
assert.strictEqual(elemento('confirmacao-exclusao-inativar').style.display, 'none');
window.ativar_terceiro(7);
previa({nome: 'Animal', ativo: false, csrf_token: 'token'});
assert.strictEqual(elemento('confirmacao-exclusao-prosseguir').textContent, 'Ativar');
elemento('confirmacao-exclusao-prosseguir').onclick();
assert.strictEqual(pedido.data.acao, 'ativar');
window.confirmarExclusaoRebanho({getAttribute: chave => chave === 'data-origem' ? 'Terceiros' : '7'});
previa({nome: 'Animal', pode_excluir: true, vinculos: [], csrf_token: 'token'});
elemento('confirmacao-exclusao-prosseguir').onclick();
assert.strictEqual(pedido.method, 'POST');
assert.strictEqual(pedido.data.csrf_token, 'token');
destino();
assert.strictEqual(window.location.href, 'geral.php?pg=lista_terceiros');
console.log('OK: bloqueio no modal, entrada pelo rebanho, POST com token e retorno à lista.');

const interruptor = {disabled: false, getAttribute(chave) {return chave === 'data-id' ? '7' : 'true';}};
window.alternar_terceiro(interruptor);
assert.strictEqual(interruptor.disabled, true);
previa({csrf_token: 'token'});
assert.strictEqual(pedido.data.acao, 'inativar');
assert.strictEqual(pedido.method, 'POST');
const interruptorInativo = {disabled: false, getAttribute(chave) {return chave === 'data-id' ? '7' : 'false';}};
window.alternar_terceiro(interruptorInativo);
previa({csrf_token: 'token'});
assert.strictEqual(pedido.data.acao, 'ativar');
console.log('OK: interruptor único ativa e inativa com POST e token.');
